services:
  db:
    image: postgres:16
    environment:
      POSTGRES_DB: order_service_db
      POSTGRES_USER: postgres
      POSTGRES_PASSWORD: postgres
    ports:
      - '127.0.0.1:5435:5432'
    volumes:
      - postgres-data:/var/lib/postgresql/data

  app:
    build: .
    image: order-service:latest
    depends_on:
      - db
    environment:
      SPRING_DATASOURCE_URL: jdbc:postgresql://db:5432/order_service_db
      SPRING_DATASOURCE_USERNAME: postgres
      SPRING_DATASOURCE_PASSWORD: postgres

    ports:
      - '8083:8079'
    restart: unless-stopped

volumes:
  postgres-data: